### ISSUE TITLE
[1.12.2] NPE Lock/Crash

### ISSUE THREAD

**Issue by notfood** [TehNut-Mods/HWYLA#111]
#### Issue Description:
I'm a modpack author. The modpack isn't big. This NPE crash on Windows, lock on Linux seems to happen randomly, we haven't been able to detect the pattern. My guess is Waila Harvestability interacting strangely with the animals in Animania.

#### What happens:
```
java.lang.NullPointerException: Unexpected error
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:142)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:73)
	at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:57)
	at mcp.mobius.waila.overlay.DecoratorRenderer.onRenderWorldLast(DecoratorRenderer.java:27)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_62_DecoratorRenderer_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:168)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1430)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

#### Steps to reproduce:

1. Look at animal
2. Try to milk
3. Randomly Crash or Lock

Disabling HWYLA prevents the crash.

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.8.23-B38
- Minecraft: 1.12.2
- Forge: 14.23.2.2611

#### Possible Conflicting Mods (Provide their version, as well)
- Animania: 1.4.5
- Waila Harvestability: 1.1.12

[crash-2018-02-05_14.26.36-client.txt](https://github.com/TehNut/HWYLA/files/1708010/crash-2018-02-05_14.26.36-client.txt)

**Comment by TehNut** [comment]
Somebody is returning null in `getPickBlock()`. This is not a hwyla error.
