### ISSUE TITLE
Console spam with Xeno's reliquary pedestal

### ISSUE THREAD

**Issue by LemADEC** [TehNut-Mods/HWYLA#115]
#### Issue Description:
Console spamming NPE in HUDHandlerTank when looking at a Xeno's reliquary pedestal.
Issue isn't reproduced with the 'view only' version of the pedestal.
Issue is reproduced on both single player and dedicated server setups.

#### What happens:
Console spam while looking at the pedestal
```
[23:10:46] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_92]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_92]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
	at mcp.mobius.waila.addons.capability.HUDHandlerTank.getNBTData(HUDHandlerTank.java:58) ~[HUDHandlerTank.class:?]
	at mcp.mobius.waila.network.MessageRequestTile$Handler$1.run(MessageRequestTile.java:97) ~[MessageRequestTile$Handler$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_92]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
```

#### What you expected to happen:
No console spam

#### Steps to reproduce:
1. Place a Xeno's reliquary pedestal
2. Look at pedestal

#### Affected Versions:
- Hwyla: 1.8.17-B31_1.10.2
- Minecraft 1.10.2
- Forge: 12.18.3.2511

#### Possible Conflicting Mods (Provide their version, as well)
- Reliquary-1.10.2-1.3.3.664

**Comment by TehNut** [comment]
They are returning a null fluid cap after saying they have one. This is an issue on their end.
