### ISSUE TITLE
Crash after changing key binding

### ISSUE THREAD

**Issue by drzpk** [TehNut-Mods/HWYLA#127]
#### Issue Description:
I was modifying key bindings and when I had changed a binding in the Hwyla's section, game crashed. Moreover, game kept crashing at startup when I tried to run it again. Only deleting all Hwyla key bindings from the *.minecraft/options.txt* file helped, but that's not a real solution.

#### What happens:
Crash log:
```
java.lang.IndexOutOfBoundsException: null
	at java.nio.Buffer.checkIndex(Unknown Source) ~[?:1.8.0_131]
	at java.nio.DirectByteBuffer.get(Unknown Source) ~[?:1.8.0_131]
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:56) ~[WailaTickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_219_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343) ~[FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

#### Steps to reproduce:

1.  Install Hwyla 1.8.26-B41_1.12.2
2. Set the following key bindings in the *.minecraft/options.txt* file (replace existing):
```
key_waila.keybind.wailaconfig:82
key_waila.keybind.wailadisplay:-99
key_waila.keybind.liquid:80
key_waila.keybind.recipe:81
key_waila.keybind.usage:75
```
3. Start the game and wait for a crash

____
#### Affected Versions:

- Hwyla: 1.8.26-B41_1.12.2
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2738

**Comment by mentimjojo** [comment]
I have had the same issues just know. See crash report.

https://paste.dimdev.org/ucelotapud.mccrash
