### ISSUE TITLE
Conflict with Energy Transfer node from Cyclic

### ISSUE THREAD

**Issue by ChaoticLogic** [TehNut-Mods/HWYLA#129]
#### Issue Description:
After placing an Energy Transfer Node block from the mod Cyclic, hwyla generates 4600 lines of repeating error code.  Cyclic's mod author has already been notified.

#### What happens:
Error log spam

#### What you expected to happen:
No errors

#### Steps to reproduce:

1. Install cyclic v 1.17.2
2. Install hwyla v 1.8.26
3.  Place Energy Transfer Node block
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.8.26
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Possible Conflicting Mods (Provide their version, as well)

Minecraft log attached. Errors begin on block place on line 2734 and proceed until end of log (4600+ lines of error message)

Key entry:

> Caused by: java.lang.NullPointerException
	at mcp.mobius.waila.addons.capability.HUDHandlerTank.getNBTData(HUDHandlerTank.java:61) ~[HUDHandlerTank.class:?]
	at mcp.mobius.waila.network.MessageRequestTile$Handler.lambda$onMessage$0(MessageRequestTile.java:93) ~[MessageRequestTile$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]

[ChaoticLogic log file.txt](https://github.com/TehNut/HWYLA/files/2453236/ChaoticLogic.log.file.txt)

**Comment by TheComputerizer** [comment]
I was wondering what those error messages spamming the console were. But I mean its not really breaking the server so do I need to do anything about this? Also can I even do anything or is this a bug?

**Comment by TehNut** [comment]
This is caused by Cyclic having mismatching logic in `hasCapability` and `getCapability`
