### ISSUE TITLE
It just crashes...I've went back 3 file versions.

### ISSUE THREAD

**Issue by Kilroy5150** [TehNut-Mods/HWYLA#130]
I don't know enough, about code, to properly lay it out so here's my crash report:

[23:06:40] [main/INFO] [FML]: Forge Mod Loader version 14.23.4.2705 for Minecraft 1.12.2 loading

---- Minecraft Crash Report ----

WARNING: coremods are present:
  RBLoadingPlugin (RealBench-Mod-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  CXLibraryCore (CXLibrary-1.12.1.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.16.jar)
  DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  ItemPatchingLoader (ItemPhysic Lite 1.3.7 mc1.12.2.jar)
  ObfuscatePlugin (Obfuscate-Mod-1.12.2.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 10/8/18 11:07 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Waila (waila)
Caused by: java.lang.NoSuchMethodError: mcp.mobius.waila.api.IWailaRegistrar.registerHeadProvider(Lmcp/mobius/waila/api/IWailaEntityProvider;Ljava/lang/Class;)V
	at mcp.mobius.waila.addons.core.PluginCore.register(PluginCore.java:28)
	at mcp.mobius.waila.proxy.ProxyCommon.loadComplete(ProxyCommon.java:60)
	at mcp.mobius.waila.Waila.loadComplete(Waila.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 742516024 bytes (708 MB) / 2183036928 bytes (2081 MB) up to 32817545216 bytes (31297 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx31310M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 Optifine OptiFine_1.12.2_HD_U_E1 82 mods loaded, 82 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                                           | Version              | Source                                                       | Signature                                |
	|:------- |:-------------------------------------------- |:-------------------- |:------------------------------------------------------------ |:---------------------------------------- |
	| UCHIJA  | minecraft                                    | 1.12.2               | minecraft.jar                                                | None                                     |
	| UCHIJA  | mcp                                          | 9.42                 | minecraft.jar                                                | None                                     |
	| UCHIJA  | FML                                          | 8.0.99.99            | forge-1.12.2-14.23.4.2705.jar                                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | forge                                        | 14.23.4.2705         | forge-1.12.2-14.23.4.2705.jar                                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | itemphysic                                   | 1.4.0                | minecraft.jar                                                | None                                     |
	| UCHIJA  | com.elytradev.movingworld.common.asm.coremod |                      | minecraft.jar                                                | None                                     |
	| UCHIJA  | obfuscate                                    | 0.2.4                | minecraft.jar                                                | None                                     |
	| UCHIJA  | additionalstructures                         | 1.5.0                | Additional+Structures+1.12.2+by+XxRexRaptorxX++(v.1.5.0).jar | None                                     |
	| UCHIJA  | adventurepack                                | 1.5.0                | Adventure-Tools-Mod-1.12.2.jar                               | None                                     |
	| UCHIJA  | craftstudioapi                               | 1.0.0                | CraftStudio-API-1.12.1.jar                                   | None                                     |
	| UCHIJA  | animania                                     | 1.5.1.1              | Animania-Mod-1.12.2.jar                                      | None                                     |
	| UCHIJA  | baubles                                      | 1.5.2                | Baubles-Mod-1.12.2.jar                                       | None                                     |
	| UCHIJA  | betterquesting                               | 3.5.269              | BetterQuesting-3.5.269.jar                                   | None                                     |
	| UCHIJA  | bibliocraft                                  | 2.4.5                | BiblioCraft-Mod-1.12.2.jar                                   | None                                     |
	| UCHIJA  | zawa                                         | 1.12.2-1.4.0         | zawa+-+1.4.0+(1.12.2).jar                                    | None                                     |
	| UCHIJA  | bookworm                                     | 1.12.2-1.0.0         | Bookworm-API-1.12.2.jar                                      | None                                     |
	| UCHIJA  | chameleon                                    | 1.12-4.1.3           | Chameleon-Library-1.12.jar                                   | None                                     |
	| UCHIJA  | coralreef                                    | 2.0                  | Coral-Reef-Mod-1.12.2.jar                                    | None                                     |
	| UCHIJA  | cw                                           | 1.0.1                | Creature-Whisperer-Mod-1.12.2.jar                            | None                                     |
	| UCHIJA  | cxlibrary                                    | 1.6.1                | CXLibrary-1.12.1.jar                                         | None                                     |
	| UCHIJA  | movingworld                                  | 1.12-6.342           | movingworld-1.12-6.342-full.jar                              | None                                     |
	| UCHIJA  | davincisvessels                              | @DVESSELSVER@        | Davincis-Vessels-Mod-1.12.jar                                | None                                     |
	| UCHIJA  | dungeontactics                               | DT-0.14.9            | Dungeon-Tactics-Mod-1.12.2.jar                               | None                                     |
	| UCHIJA  | dynamiclights                                | 1.4.9                | DynamicLights-1.12.2.jar                                     | None                                     |
	| UCHIJA  | dynamiclights_onfire                         | 1.0.7                | DynamicLights-1.12.2.jar                                     | None                                     |
	| UCHIJA  | dynamiclights_creepers                       | 1.0.6                | DynamicLights-1.12.2.jar                                     | None                                     |
	| UCHIJA  | dynamiclights_dropitems                      | 1.1.0                | DynamicLights-1.12.2.jar                                     | None                                     |
	| UCHIJA  | dynamiclights_entityclasses                  | 1.0.1                | DynamicLights-1.12.2.jar                                     | None                                     |
	| UCHIJA  | dynamiclights_mobequipment                   | 1.1.0                | DynamicLights-1.12.2.jar                                     | None                                     |
	| UCHIJA  | dynamiclights_flamearrows                    | 1.0.1                | DynamicLights-1.12.2.jar                                     | None                                     |
	| UCHIJA  | dynamiclights_floodlights                    | 1.0.3                | DynamicLights-1.12.2.jar                                     | None                                     |
	| UCHIJA  | dynamiclights_otherplayers                   | 1.0.9                | DynamicLights-1.12.2.jar                                     | None                                     |
	| UCHIJA  | dynamiclights_theplayer                      | 1.1.3                | DynamicLights-1.12.2.jar                                     | None                                     |
	| UCHIJA  | dsurround                                    | 3.4.9.16             | DynamicSurroundings-1.12.2-3.4.9.16.jar                      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJA  | presets                                      | 3.4.9.16             | DynamicSurroundings-1.12.2-3.4.9.16.jar                      | None                                     |
	| UCHIJA  | exoticbirds                                  | 1.0                  | Exotic-Birds-Mod-1.12.2.jar                                  | None                                     |
	| UCHIJA  | golems                                       | 7.0.0-beta1          | Extra-Golems-Mod-1.12.2.jar                                  | None                                     |
	| UCHIJA  | fairylights                                  | 2.1.4                | FairyLights-1.12.jar                                         | None                                     |
	| UCHIJA  | ftfloocraft                                  | 1.8                  | Floocraft-Mod-1.12.2.jar                                     | None                                     |
	| UCHIJA  | forgelin                                     | 1.7.4                | Forgelin-1.7.4.jar                                           | None                                     |
	| UCHIJA  | hud                                          | 1.4-beta             | hud-1.4-beta-1.12.2.jar                                      | None                                     |
	| UCHIJEE | waila                                        | 1.8.25               | Hwyla-1.8.25-B40_1.12.jar                                    | None                                     |
	| UCHIJ   | llibrary                                     | 1.7.15               | LLibrary-1.12.2.jar                                          | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJ   | iceandfire                                   | 1.3.1                | Ice-and-Fire-Mod-1.12.2.jar                                  | None                                     |
	| UCHIJ   | infinitylib                                  | 1.12.2-1.12.0        | InfinityLib-1.12.2.jar                                       | None                                     |
	| UCHIJ   | mantle                                       | 1.12-1.3.2.24        | Mantle-Mod-1.12.2.jar                                        | None                                     |
	| UCHIJ   | inspirations                                 | 1.12.2-0.1.2         | Inspirations-Mod-1.12.2.jar                                  | None                                     |
	| UCHIJ   | joshxmas                                     | 1.12.2-1.1.1         | Joshuas-Christmas-Mod-1.12.2.jar                             | None                                     |
	| UCHIJ   | jaff                                         | 1.7_for_1.12         | Just-a-Few-Fish-Mod-1.12.jar                                 | None                                     |
	| UCHIJ   | lsc                                          | 0.6.1.0-alpha        | Loot-Slash-Conquer-Mod-1.12.2.jar                            | None                                     |
	| UCHIJ   | minecolonies                                 | 1.12.2-0.9.4-RELEASE | minecolonies-1.12.2-0.9.4-RELEASE-universal.jar              | None                                     |
	| UCHIJ   | movillages                                   | 1.5.4                | Mo-Villages-Mod-1.12.2.jar                                   | None                                     |
	| UCHIJ   | multihotbar                                  | 3.0                  | MultiHotbar-1.12.jar                                         | None                                     |
	| UCHIJ   | mysticalwildlife                             | 1.1.3                | mysticalwildlife-1.12.2-1.1.3.jar                            | None                                     |
	| UCHIJ   | overlord                                     | 2.4.7                | Overlord-Mod-1.12.jar                                        | None                                     |
	| UCHIJ   | pmp                                          | 1.12.1               | Plant-Mega-Pack-Mod-1.12.2.jar                               | None                                     |
	| UCHIJ   | radixcore                                    | 1.12.x-2.2.1         | RadixCore-1.12.x-2.2.1-universal.jar                         | None                                     |
	| UCHIJ   | realworld                                    | 1.18                 | RealWorld-Mod-1.12.2.jar                                     | None                                     |
	| UCHIJ   | reforged                                     | 0.7.5                | Reforged-Mod-1.12.jar                                        | None                                     |
	| UCHIJ   | reptilemod                                   | 3.8.4                | reptilemod-1.12.2-3.8.4-86.jar                               | None                                     |
	| UCHIJ   | roguelike                                    | 1.8.0                | RoguelikeDungeons-1.12.2-1.8.0.jar                           | None                                     |
	| UCHIJ   | ruins                                        | 17.1                 | Ruins-1.12.2.jar                                             | None                                     |
	| UCHIJ   | shadowmc                                     | 3.8.0                | ShadowMC-1.12.jar                                            | None                                     |
	| UCHIJ   | shipwrecks_winslow                           | 2.0.0                | shipwrecks-mc1.12.2-2.0.0.jar                                | None                                     |
	| UCHIJ   | simpledivegear                               | 1.0.3                | SimpleDivingGear-1.0.3+mc+1.12.2.jar                         | None                                     |
	| UCHIJ   | spartanweaponry                              | beta 1.1             | Spartan-Weaponry-Mod-1.12.2.jar                              | None                                     |
	| UCHIJ   | bq_standard                                  | 3.4.145              | StandardExpansion-3.4.145.jar                                | None                                     |
	| UCHIJ   | stepup                                       | 1.0.2-mc1.10-1.12.2  | StepUp-1.0.2-mc1.10-1.12.jar                                 | None                                     |
	| UCHIJ   | storagedrawers                               | 1.12-5.2.5           | Storage-Drawers-Mod-1.12.jar                                 | None                                     |
	| UCHIJ   | tfa                                          | 1.1.2                | TFA+1.3.jar                                                  | None                                     |
	| UCHIJ   | tconstruct                                   | 1.12.2-2.9.0.55      | Tinkers-Construct-Mod-1.12.2.jar                             | None                                     |
	| UCHIJ   | tombmanygraves                               | @VERSION@            | Tomb-Many-Graves-2-Mod-1.12.1.jar                            | None                                     |
	| UCHIJ   | torohealthmod                                | 1.12.2-11            | torohealth-1.12.2-11.jar                                     | None                                     |
	| UCHIJ   | trapcraft                                    | v2.4.3a              | Trapcraft-Mod-1.12.jar                                       | None                                     |
	| UCHIJ   | treechopper                                  | 1.2.4                | TreeChopper-1.12.2-1.2.4.jar                                 | None                                     |
	| UCHIJ   | uteamcore                                    | 2.0.0.81             | U-Team-Core-1.12.2.jar                                       | None                                     |
	| UCHIJ   | usefulbackpacks                              | ${version}           | Useful-Backpacks-Mod-1.12.2.jar                              | None                                     |
	| UCHIJ   | thejungle                                    | 1.011.1222           | Welcome-to-the-Jungle-Mod-1.12.2.jar                         | None                                     |
	| UCHIJ   | xpfromharvest                                | 1.0                  | XP-From-Harvest-Mod-1.12.2.jar                               | None                                     |
	| UCHIJ   | zoocraftdiscoveries                          | 1.0                  | Zoocraft+Discoveries+1.12.2-1.2.0.jar                        | None                                     |
	| UCHIJ   | ladylib                                      | 2.1                  | Ladylib-2.1.jar                                              | None                                     |
	| UCHIJ   | lumen                                        | 0.4.0                | Lumen-Mod-1.12.2.jar                                         | None                                     |

	Loaded coremods (and transformers): 
RBLoadingPlugin (RealBench-Mod-1.12.2.jar)
  pw.prok.realbench.asm.RBTransformer
ForgelinPlugin (Forgelin-1.7.4.jar)
  
CXLibraryCore (CXLibrary-1.12.1.jar)
  cubex2.cxlibrary.CoreModTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.16.jar)
  org.blockartistry.DynSurround.asm.Transformer
DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
ItemPatchingLoader (ItemPhysic Lite 1.3.7 mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
ObfuscatePlugin (Obfuscate-Mod-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 416.16' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Pulsar/inspirations loaded Pulses: 
		- InspirationsShared (Enabled/Forced)
		- InspirationsBuilding (Enabled/Not Forced)
		- InspirationsUtility (Enabled/Not Forced)
		- InspirationsRecipes (Enabled/Not Forced)
		- InspirationsTweaks (Enabled/Not Forced)
		- InspirationsShared (Enabled/Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

**Comment by EverSoul** [comment]
I got this issue too, have any idea why?

**Comment by TehNut** [comment]
Can't do much from this log, but if I had to guess, somebody is shipping a bad Waila API in their jar. Unless you can reproduce this with just Hwyla on it's own, I don't think I'll be looking into it more.

**Comment by Kilroy5150** [comment]
I've come to discover one thing: There are some mods, even if they aren't (in any way), associated with this mod, that will just "crash" it so i went to the process of removing recently added mods and (after a bit of this) i realized it was a random mod i've downloaded. 

What scary about Minecraft is: I'm using an I7, with 32GB, and a GeForce 1050TI card and the code (Forge) is SO poorly written that it's crashing like it was Red Dead 2 on Steroids. I don't know if it's bad memory management or what but my machine should CRUCIFY Minecraft..instead it struggles with the graphics at times like it's 10 years old. I can pull back on most of the settings and it still struggles in some places....that's got to be poorly written code. I'm playing AAA list video games that are ramped to the nines and this game makes it act like a Tandy Color Computer 3...

There's something inherently wrong with that particular situation and it's not my hardware.

**Comment by EverSoul** [comment]
I reinstalled everything and the issue was resolved. I have no idea what I did but I never received this crash again.
