### ISSUE TITLE
Error screen upon game loading

### ISSUE THREAD

**Issue by Nexoris** [TehNut-Mods/HWYLA#189]
#### Issue Description:
After launching the game from the Minecraft launcher, it displays an error screen. It says:
"Waila (waila) has failed to load correctly
net/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent"

#### What happens:
After the initial white "Mojang" loading screen, an error screen shows up.

#### What you expected to happen:
I... expected not an error screen?

#### Steps to reproduce:

1. have "hwyla-forge-1.10.4-B65_1.14.2.jar" in the minecraft mod folder
2. select "forge (1.14.4-forge-28.0.45" and click "Play"
3. ... voila?
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: Hwyla-forge-1.10.4-B65_1.14.2
- Minecraft: 1.14.4
- Forge: 28.0.45

#### Possible Conflicting Mods (Provide their version, as well)

Currently I have no other mods in my mod folder, to make sure it was just this mod.

**Comment by SDPhantom** [comment]
Apparently, Forge changed the loading process starting with 28.0.45. They advise modders to update their code. https://www.minecraftforge.net/forum/topic/74214-error-loading-mods/

For now, it should be fine if you backpedal to Forge 28.0.41

Error Log:
> [modloading-worker-4/ERROR]: Failed to create mod instance. ModID: waila, class mcp.mobius.waila.Waila
java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_51]
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_51]
	at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_51]
	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:86) ~[eventbus-0.10.6-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:114) ~[eventbus-0.10.6-service.jar:?]
	at mcp.mobius.waila.Waila.<init>(Waila.java:58) ~[?:1.10.4-B65_1.14.2]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) [?:28.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$1998/307307754.accept(Unknown Source) [?:28.0]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$1997/110932276.accept(Unknown Source) [?:1.8.0_51]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$1997/110932276.accept(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:133) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2089/1415761574.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_51]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.gameevent.PlayerEvent$PlayerLoggedInEvent
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:102) ~[modlauncher-3.2.0.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	... 31 more

**Comment by bloodconfetti** [comment]
[crash-2019-08-09_00.06.41-server.txt](https://github.com/TehNut/HWYLA/files/3484982/crash-2019-08-09_00.06.41-server.txt)

**Comment by TehNut** [comment]
I don't know why you think that is related to me.

**Comment by bloodconfetti** [comment]
> 
> 
> I don't know why you think that is related to me.

Is it not? I'm sorry... I loaded your mod into my folder and then upon upload the game crashed.
