### ISSUE TITLE
[1-15-pre4 Fabric] Crash when entering a Newly Generated world

### ISSUE THREAD

**Issue by Gbergz** [TehNut-Mods/HWYLA#207]
#### Issue Description:
[1-15-pre4 Fabric] Crash when entering a Newly Generated world or entering an existing world from pre-3

#### What happens:
Joining a world w/ Hwyla installed makes the game crash.

#### What you expected to happen:
Joining the world without any issues.

### Crash report:
[https://paste.ee/p/xA0C4](https://paste.ee/p/xA0C4)

#### Steps to reproduce:

1. Boot up the game w/ Hwyla installed
2. Create a world
3. Wait..
- Crash!

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.9.18-69
- Minecraft: 1.15-Pre4
- Fabric: 1.15-pre4+build.1_yarn-0.7.2+build.174

#### Possible Conflicting Mods (Provide their version, as well)
None using only Hwyla & Fabric API

#### EDIT:
The crash only happens when you're looking at a block / entity. When the thing that tells you what it is you're looking at comes up you crash immediately.

**Comment by Issacozzman** [comment]
Same Game crashes with 1.15 Pre  4 ---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 12/3/19 6:55 PM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.class_308.method_1453(Lnet/minecraft/class_1159;)V
	at mcp.mobius.waila.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:91)
	at mcp.mobius.waila.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:60)
	at mcp.mobius.waila.overlay.WailaTickHandler.renderOverlay(WailaTickHandler.java:60)
	at net.minecraft.class_757.handler$zep000$renderOverlay(class_757.java:1391)
	at net.minecraft.class_757.method_3192(class_757.java:585)
	at net.minecraft.class_310.method_1523(class_310.java:941)
	at net.minecraft.class_310.method_1514(class_310.java:576)
	at net.minecraft.client.main.Main.main(Main.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mcp.mobius.waila.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:91)
	at mcp.mobius.waila.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:60)
	at mcp.mobius.waila.overlay.WailaTickHandler.renderOverlay(WailaTickHandler.java:60)
	at net.minecraft.class_757.handler$zep000$renderOverlay(class_757.java:1391)

-- Affected level --
Details:
	All players: 2 total; [class_746['IssacOzzman'/599, l='MpServer', x=186.70, y=68.56, z=84.30], class_745['EmeraldOnxy'/172, l='MpServer', x=224.59, y=62.51, z=69.26]]
	Chunk stats: Client Chunk Cache: 729, 500
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: -6347512123569642201
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (240,64,96), Chunk: (at 0,4,0 in 15,6; contains blocks 240,0,96 to 255,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 20621113 game time, 5835432 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:450)
	at net.minecraft.class_310.method_1587(class_310.java:1865)
	at net.minecraft.class_310.method_1514(class_310.java:596)
	at net.minecraft.client.main.Main.main(Main.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.15 Pre-release 4
	Minecraft Version ID: 1.15-pre4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1135953440 bytes (1083 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amecs: Amecs 1.2.6+1.15-pre2
		autoconfig1u: Auto Config v1 Updated 1.2.3
		blue_endless_jankson: jankson +
		cloth: Cloth Events 1.0.1-unstable.201911010702
		cloth-config2: Cloth Config v2 2.4-unstable.201911031154
		fabric: Fabric API 0.4.19+build.272-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825db3
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.4+06c939b3b3
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea89b3
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825db3
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825db3
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825db3
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825db3
		fabric-dimensions-v1: fabric-dimensions-v1 0.2.3+06c939b3b3
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.2.6+12515ed9b3
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825db3
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e1b3
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+591e97ae42
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a7305b3
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825db3
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d6b3
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a7305b3
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed9b3
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c3b3
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d6b3
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141bb3
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.7+f3d8141bb3
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.18+ec40b2e1b3
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a60b3
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825db3
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed9b3
		fabric-rendering-v0: Fabric Rendering (v0) 1.0.1+b7f9825db3
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b3b3
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.2+b7f9825db3
		fabric-textures-v0: Fabric Textures (v0) 1.0.3+06c939b3b3
		fabricloader: Fabric Loader 0.7.2+build.174
		inventorysorter: Inventory Sorter 1.6.0
		leaf-decay: Leaf Decay ${version}
		lightoverlay: Light Overlay 3.6.1
		minecraft: Minecraft 1.15-rc.4
		modmenu: Mod Menu 1.8.0.1.15-pre3+build.14
		mousewheelie: Mouse Wheelie 1.3.6+1.15-pre3
		roughlyenoughitems: Roughly Enough Items 3.2.12-unstable.201911261311
		tweed: Tweed API 2.2.8
		waila: Hwyla 1.9.18
	Launched Version: fabric-loader-0.7.2+build.174-1.15-pre4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.20, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/ChromaHills-128x-1.14-v2 (1).zip (incompatible), file/ModernArch R24 [1.13 - 1.15] [512x].zip (incompatible), file/RUDY V03 512x MC 1_14.zip (incompatible)
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 2700X Eight-Core Processor
