### ISSUE TITLE
Tool kit hangs on line 36 

### ISSUE THREAD

**Issue by tylermasci16** [TehNut-Mods/HWYLA#218]
https://github.com/TehNut/HWYLA/blob/048e1e33ffd747053945666ff202b94a8b9266be/src/main/java/mcp/mobius/waila/overlay/Tooltip.java#L36

**Comment by tylermasci16** [comment]
It froze  java.lang.Thread.State: RUNNABLE
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        - locked <0x0000000740194500> (a java.util.Vector)
        - locked <0x0000000740190df0> (a java.util.Vector)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        - locked <0x000000074016d478> (a java.lang.Runtime)
        at java.lang.System.load(System.java:1086)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        - locked <0x0000000740194500> (a java.util.Vector)
        - locked <0x0000000740190df0> (a java.util.Vector)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        - locked <0x000000074016d478> (a java.lang.Runtime)
        at java.lang.System.loadLibrary(System.java:1122)
        at java.awt.Toolkit$3.run(Toolkit.java:1636)
        at java.awt.Toolkit$3.run(Toolkit.java:1634)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Toolkit.loadLibraries(Toolkit.java:1633)
        at java.awt.Toolkit.<clinit>(Toolkit.java:1670)
        at java.awt.Dimension.<clinit>(Dimension.java:88)
        at mcp.mobius.waila.overlay.Tooltip.<init>(Tooltip.java:36)
        at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:68)
        at mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:112)
        at net.minecraftforge.eventbus.ASMEventHandler_173_WailaClient_onClientTick_ClientTickEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
        at net.minecraftforge.fml.hooks.BasicEventHooks.onPostClientTick(BasicEventHooks.java:109)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1395)
        at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:869)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
        at net.minecraft.client.main.Main.main(SourceFile:155)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
        at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$398/1656303750.call(Unknown Source)
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

Trying to load awt lib on mac
Can you fix by remove java awt dimesion

**Comment by tylermasci16** [comment]
JVM: OpenJDK GraalVM CE 19.0.0 (25.212-b03-jvmci-19-b01, mixed mode)
Java: version 1.8.0_212, vendor Oracle Corporation
Java Home: /Library/Java/JavaVirtualMachines/graalvm-ce-19.0.0/Contents/Home/jre

**Comment by tylermasci16** [comment]
Problem seem happened on other mod 
also not have bug - Closed
