### ISSUE TITLE
Game crash when looking at Player Heads spawned via UUID

### ISSUE THREAD

**Issue by StarsDown64** [TehNut-Mods/HWYLA#236]
Ref as well to [Issue 235](https://github.com/TehNut/HWYLA/issues/235)

#### What happens:
When looking at a player head that has been spawned in with a UUID, the game will crash with the following error:
```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 4/2/20 1:10 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.class_2519.method_23256(class_2519.java:56)
	at net.minecraft.class_2487.method_10582(class_2487.java:172)
	at mcp.mobius.waila.addons.minecraft.HUDHandlerVanilla.getStack(HUDHandlerVanilla.java:47)
	at mcp.mobius.waila.overlay.RayTracing.handleStackProviders(RayTracing.java:155)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:133)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:73)
	at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:55)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:86)
	at net.minecraft.class_310.handler$zfi000$clientTick(class_310.java:6532)
	at net.minecraft.class_310.method_1574(class_310.java:1405)
	at net.minecraft.class_310.method_1523(class_310.java:964)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2519.method_23256(class_2519.java:56)
	at net.minecraft.class_2487.method_10582(class_2487.java:172)
	at mcp.mobius.waila.addons.minecraft.HUDHandlerVanilla.getStack(HUDHandlerVanilla.java:47)
	at mcp.mobius.waila.overlay.RayTracing.handleStackProviders(RayTracing.java:155)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:133)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:73)
	at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:55)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:86)
	at net.minecraft.class_310.handler$zfi000$clientTick(class_310.java:6532)

-- Affected level --
Details:
	All players: 3 total; [class_746['StarsDown64'/1393649, l='MpServer', x=750.53, y=56.50, z=-29.68], class_745['ComplexFlips'/1312279, l='MpServer', x=724.54, y=43.00, z=8.30], class_745['VeritasDL'/909043, l='MpServer', x=752.47, y=57.00, z=-73.05]]
	Chunk stats: Client Chunk Cache: 529, 352
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: -469229712002101309
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (160,64,208), Chunk: (at 0,4,0 in 10,13; contains blocks 160,0,208 to 175,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 44061 game time, 258042827 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:611)
	at net.minecraft.class_310.method_1587(class_310.java:1921)
	at net.minecraft.class_310.method_1514(class_310.java:639)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
```

#### What you expected to happen:
HWYLA would display information that says "Player Head", and not crash

#### Steps to reproduce:

1. Spawn in a player head with the following properties: `SkullOwner:{Id:"SampleIdHere"}`
2. Place it down
3. Look at it so that HWYLA attempts to display information
4. Freeze for 2 seconds and then crash

If you need a sample Id, look up your own UUID. The crash occurs with custom Ids from databases like minecraft-heads.com and with valid player UUIDs.
...

____
#### Affected Versions (Do *not* use "latest"):

This is simply my current version, which is the latest to date,
- Hwyla: 1.9.21-72
- Minecraft: 1.15.2
- Fabric: 0.7.10+build.191-1.15.2

**Comment by NoobChester** [comment]
yea that's probably the issue I encountered in #235

**Comment by bighagrid** [comment]
Same issue here.

Minecraft 1.15.2
Fabric 0.8.2+build.194-1.15.2
Hwyla 1.9.21-72

**Comment by TehNut** [comment]
I think I'm too stupid to figure out commands enough to spawn in a skull with a UUID. I can get it to work with my player name just fine, but UUID is just giving me a Steve head.

E: I just used the generator from minecraft-heads.

**Comment by StarsDown64** [comment]
The UUID does not attach a skin necessarily, I had the same effect when spawning in one with my own UUID. However, the crash still occurs. Try this command, I can confirm it causes a crash: `/give @p minecraft:player_head{SkullOwner:{Id:"2194fa66-eb0a-41e1-ab95-bd0e383dfe24"}}`
Side note: Somehow the dashes in the ID are important, it wouldn't crash if it didn't have them
