### ISSUE TITLE
Crash when loading world

### ISSUE THREAD

**Issue by LukeNotDuke** [TehNut-Mods/HWYLA#256]
#### Issue Description:
Crash when loading world in fabric 1.16 - Pre-release 5 
#### What Happens:
The Game Crashes .
#### What you expected to happen:
The world would load up and Hwyla should show what block I am looking at.
#### Steps to reproduce:
1. Download Fabric API 0.12.1 ( 1.16 Pre release 5 ) and install Fabric 0.5.2.40 1.16- Pre release 5 .
2. Open the fabric profile you just installed and load an old / new world .
#### Affected Versions:
- Hwyla: 1.9.22
- Minecraft: 1.16 Pre-release 5
- Fabric: 0.5.2.40
#### Possible Conflicting Mods:
Appleskin(Mc1.16-fabric-1.0.10)
Crash Log:
---- Minecraft Crash Report ----
// There are four lights!

Time: 6/13/20 2:26 PM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.class_2561.method_10863()Ljava/lang/String;
	at mcp.mobius.waila.overlay.Tooltip.getLineSize(Tooltip.java:106)
	at mcp.mobius.waila.overlay.Tooltip.lambda$computeLines$0(Tooltip.java:43)
	at mcp.mobius.waila.overlay.Tooltip$$Lambda$4772/823208220.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at mcp.mobius.waila.overlay.Tooltip.computeLines(Tooltip.java:42)
	at mcp.mobius.waila.overlay.Tooltip.<init>(Tooltip.java:37)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:96)
	at net.minecraft.class_310.handler$zdi000$clientTick(class_310.java:5288)
	at net.minecraft.class_310.method_1574(class_310.java:1464)
	at net.minecraft.class_310.method_1523(class_310.java:994)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mcp.mobius.waila.overlay.Tooltip.getLineSize(Tooltip.java:106)
	at mcp.mobius.waila.overlay.Tooltip.lambda$computeLines$0(Tooltip.java:43)
	at mcp.mobius.waila.overlay.Tooltip$$Lambda$4772/823208220.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at mcp.mobius.waila.overlay.Tooltip.computeLines(Tooltip.java:42)
	at mcp.mobius.waila.overlay.Tooltip.<init>(Tooltip.java:37)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:96)
	at net.minecraft.class_310.handler$zdi000$clientTick(class_310.java:5288)

-- Affected level --
Details:
	All players: 1 total; [class_746['JilterSmelter'/273, l='ClientLevel', x=10.50, y=64.00, z=22.50]]
	Chunk stats: Client Chunk Cache: 441, 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,63,32), Chunk: (at 0,3,0 in 1,2; contains blocks 16,0,32 to 31,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 81 game time, 81 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2176)
	at net.minecraft.class_310.method_1514(class_310.java:677)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16 Pre-release 5
	Minecraft Version ID: 1.16-pre5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1237612136 bytes (1180 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 1.0.10
		fabric: Fabric API 0.12.1+build.361-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c2f
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea8662f
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea892f
		fabric-command-api-v1: Fabric Command API (v1) 1.0.6+4e84b64f2f
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308362f
		fabric-containers-v0: Fabric Containers (v0) 0.1.7+d249f7b62f
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8662f
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d2f
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b30532f
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f2f
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.3+0d474ec42f
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96362f
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+e16a97742f
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c52f
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.10+059ea8662f
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce992f
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d62f
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b2f
		fabric-networking-v0: Fabric Networking (v0) 0.1.9+1a47cd782f
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.4+059ea8662f
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad62f
		fabric-particles-v1: fabric-particles-v1 0.1.3+4a08d6b22f
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c2f
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb82f
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.1+059ea8662f
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a602f
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d2f
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.7+12a8474c2f
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104902f
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d72f
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.5+059ea8662f
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.5+5a6e8f4c2f
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb82f
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.3+059ea8662f
		fabricloader: Fabric Loader 0.8.7+build.201
		minecraft: Minecraft 1.16-rc.5
		waila: Hwyla 1.9.22
	Launched Version: fabric-loader-0.8.7+build.201-1.16-pre5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon (TM) R5 M330 GL version 4.6.13596 Compatibility Profile Context 20.5.1 27.20.1017.1011, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz

**Comment by LukeNotDuke** [comment]
Oops , I forgot to make Crash Log bold :p

**Comment by giveashift** [comment]
I'm having the same issue. The world loads fine but as soon as I look at anything that is close enough to prompt HWYLA to display info it crashes.

**Comment by LukeNotDuke** [comment]
The world doesnt even load for me , i think my player is looking at the ground is why though

**Comment by LukeNotDuke** [comment]
Its  clearly a HWYLA bug since i loaded up fabric without it and it worked fine ( with only apple skin )

**Comment by LukeNotDuke** [comment]
It might be a fabric bug since i tried with some other mod and the game crashed when I tried to pick block a block from the mod

**Comment by TehNut** [comment]
https://www.curseforge.com/minecraft/mc-mods/hwyla/files/2987120
