### ISSUE TITLE
"Failed to replace ModInfo instance with one that supports the mod list config"

### ISSUE THREAD

**Issue by BinaryQuantumSoul** [TehNut-Mods/HWYLA#267]
#### Issue Description:
Error in the logs when loading game

#### What happens:
```
[01:21:24] [modloading-worker-0/DEBUG] [ne.mi.fm.AutomaticEventSubscriber/LOADING]: Auto-subscribing mcp.mobius.waila.WailaClient to FORGE
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: java.lang.NoSuchMethodError: net.minecraftforge.fml.loading.moddiscovery.ModInfo.getModConfig()Lcom/electronwill/nightconfig/core/UnmodifiableConfig;
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at mcp.mobius.waila.WailaClient$WailaModInfo.<init>(WailaClient.java:117)
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at mcp.mobius.waila.WailaClient.<clinit>(WailaClient.java:47)
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at java.lang.Class.forName0(Native Method)
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at java.lang.Class.forName(Class.java:348)
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75)
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at java.util.ArrayList.forEach(ArrayList.java:1257)
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62)
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:141)
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135)
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[01:21:24] [modloading-worker-0/INFO] [STDERR/]: [mcp.mobius.waila.WailaClient:<clinit>:56]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[01:21:24] [modloading-worker-0/ERROR] [Waila/]: Failed to replace ModInfo instance with one that supports the mod list config
```

____
#### Affected Versions

- Hwyla: 1.10.8-B72
- Minecraft: 1.15.2
- Forge: 31.2.27

#### Possible Conflicting Mods (Provide their version, as well)
- Jei: 6.0.2.12

**Comment by TehNut** [comment]
Since this isn't a crash, I won't be fixing it for 1.15.2, but the relevant code has been removed for 1.16+
