### ISSUE TITLE
HWYLA requires waila

### ISSUE THREAD

**Issue by tacogerbil** [TehNut-Mods/HWYLA#302]
#### Issue Description:
Using the new Fabric API fabric-api-0.24.2+build.413-1.16 causes a crash, Could not find required mod: waila requires {fabric-command-api-v1 @ [*]} 

#### What happens:
start.bat
[14:27:47] [main/INFO]: Loading for game Minecraft 1.16.3
[14:27:47] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: waila requires {fabric-command-api-v1 @ [*]}  
        at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:170) ~[fabric-server-launch.jar:?]       
        at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:609) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:206) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:196) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_261]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_261]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_261]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
        at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:168) ~[fabric-server-launch.jar:?]       
        ... 12 more
Press any key to continue . . . 

#### What you expected to happen:
To not crash

#### Steps to reproduce:

1. Install new api
2. run server
3. crash
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: Hwyla-fabric-1.16.2-1.9.23-79
- Minecraft: Hwyla-fabric-1.16.2-1.9.23-79
- Fabric: 0.6.1.51

#### Possible Conflicting Mods (Provide their version, as well)
Literally only have Fabric API and HWYLA in the mods folder..

**Comment by tomyuk** [comment]
The same phenomenon occurs even fabric-api-0.25.0+build.415-1.16
