### ISSUE TITLE
Hwyla-fabric config interface crashes on 1.16.4

### ISSUE THREAD

**Issue by MeeniMc** [TehNut-Mods/HWYLA#305]
#### Issue Description:

Hwyla-fabric crashes when clicking any of the two 'main' buttons in the Hwyla configuration screen.

#### What happens:

```
[11:31:15] [main/FATAL]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:440) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:92) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:162) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:162) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1071) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.4-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.6+build.214.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2561.getString()" because "this.field_22754" is null
	at net.minecraft.class_339.method_25355(class_339.java:225) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at mcp.mobius.waila.gui.config.OptionsEntryButton.<init>(OptionsEntryButton.java:17) ~[Hwyla-fabric-1.16.2-1.9.23-79.jar:?]
	at mcp.mobius.waila.gui.GuiConfigPlugins.lambda$getOptions$1(GuiConfigPlugins.java:28) ~[Hwyla-fabric-1.16.2-1.9.23-79.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at mcp.mobius.waila.gui.GuiConfigPlugins.getOptions(GuiConfigPlugins.java:25) ~[Hwyla-fabric-1.16.2-1.9.23-79.jar:?]
	at mcp.mobius.waila.gui.GuiOptions.method_25423(GuiOptions.java:43) ~[Hwyla-fabric-1.16.2-1.9.23-79.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:922) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at mcp.mobius.waila.gui.GuiConfigHome.lambda$init$1(GuiConfigHome.java:26) ~[Hwyla-fabric-1.16.2-1.9.23-79.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:33) ~[intermediary-minecraft-1.16.4-client.jar:?]
```

#### What you expected to happen:
Config menu should appear, duh. :)

#### Steps to reproduce:

1. Install Minecraft 1.16.4; Fabric loader 0.10.6-b214; Fabric API 0.25.1; Modmenu 1.14.6+build31; Hwyla 1.9.23-79
2. Launch game
3. click Mods; Hwyla; 3 sliders top-right
4. click any of the two buttons (for example Waila Settings)
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.9.23-79
- Minecraft: 1.16.4
- Fabric: 0.25.1
- Modmenu: 1.14.6

#### Possible Conflicting Mods (Provide their version, as well)
Everything else removed.

**Comment by ghost** [comment]
Same on here

**Comment by marchofiron** [comment]
I can confirm this.
It  seems to work just fine, just the configs dont work properly.

**Comment by egeesin** [comment]
I think there's no need for any confirmation comments unless you have valuable info. If you having this issue, just use 👍 reaction at the OG post so you can get devs/maintainer's attention without sending everyone unnecessary notifications to the people subscribed this issue.

**Comment by MeeniMc** [comment]
@TehNut could you please merge #306 ?
