### ISSUE TITLE
Client Crash when looking at RefinedStorage Controller

### ISSUE THREAD

**Issue by GeneralUltra758** [TehNut-Mods/HWYLA#50]
#### Issue Description:
This bug does occur in a modpack (SkyFactory3) but i am reporting it here since i am absolutely certain that the cause is HWYLA since uninstalling it fixes the issue same as disabling it via numpad-1 ingame also fixes it and you instantly crash upon enabling it while looking at the problematic block as described below.
I also tried manually updating the mod but the issue still persisted in the newest available version (in curse launcher which was: 1.8.10)

#### What happens:
When looking at a Controller block from Refined Storage while the RefinedStorage system is crafting ...

EDIT:
When crafting soimething more intense and of longer duration, seems to happen if Solderer Autocrafting is involved a lot

... the client crashes (disconnects you from the server) with various errors such as: "A fatal error has occurred, this connection is terminated."
(these messages vary when trying to rejoin the server and instantly crash again(get disconnected) once looking at the controller)

#### What you expected to happen:
Not to have the client crash and disconnect me from the server

#### Steps to reproduce:

1. Make a Refined Storage System and setup some autocrafting recipes  
2. Let it autocraft something
3. While crafting is in progress look at the controller

____
#### Affected Versions:

- Hwyla: 1.8.10
- Minecraft: 1.10.2
- Forge: 12.18.3.2215
- Used Modpack SkyFactory 3.06 (HWYLA Updated manually to said version)

#### Conflicting Mod
- Refined Storage 1.2.18

**Comment by TehNut** [comment]
Can't do much without a log.

**Comment by GeneralUltra758** [comment]
error on disconnection : `Internal Exception: java.IOException: An Existing connection was forcibly closed by the remote host`

if you need more tell me what and i post it too

this is a part of the logs in fml-client-3.log

...
```
[08:12:20] [Netty Client IO #4/ERROR] [FML/]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_25]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:1.8.0_25]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_25]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_25]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[?:1.8.0_25]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446) ~[UnpooledUnsafeDirectByteBuf.class:4.0.23.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) ~[AbstractByteBuf.class:4.0.23.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225) ~[NioSocketChannel.class:4.0.23.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) [AbstractNioByteChannel$NioByteUnsafe.class:4.0.23.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [NioEventLoop.class:4.0.23.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [NioEventLoop.class:4.0.23.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [NioEventLoop.class:4.0.23.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [NioEventLoop.class:4.0.23.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:4.0.23.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[08:12:20] [Netty Client IO #4/DEBUG] [EnderCore/]: Skipping syncing field com.enderio.core.common.config.ConfigHandler.showRegistryNameTooltips as it was marked NoSync
[08:12:20] [Netty Client IO #4/DEBUG] [EnderCore/]: Skipping syncing field com.enderio.core.common.config.ConfigHandler.showOredictTooltips as it was marked NoSync
[08:12:20] [Netty Client IO #4/DEBUG] [EnderCore/]: Skipping syncing field com.enderio.core.common.config.ConfigHandler.showDurabilityTooltips as it was marked NoSync
[08:12:20] [Netty Client IO #4/INFO] [EnderCore/]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[08:12:20] [Netty Client IO #4/INFO] [MineMenu/]: CLIENT: Disconnected from server, enabling all click actions
[08:12:20] [Netty Client IO #4/INFO] [SimplyJetpacks/]: Loading configuration files
[08:12:21] [Client thread/DEBUG] [FML/]: Reverting to frozen data state.
[08:12:21] [Client thread/TRACE] [mcp/mcp]: Sending event FMLModIdMappingEvent to mod mcp
[08:12:21] [Client thread/TRACE] [mcp/mcp]: Sent event FMLModIdMappingEvent to mod mcp
[08:12:21] [Client thread/DEBUG] [FML/]: Bar Step: ModIdMapping - Minecraft Coder Pack took 0.000s
[08:12:21] [Client thread/TRACE] [FML/FML]: Sending event FMLModIdMappingEvent to mod FML
[08:12:21] [Client thread/TRACE] [FML/FML]: Sent event FMLModIdMappingEvent to mod FML
```
...

**Comment by aemondis** [comment]
Same issue here... drives me nuts as I get this randomly on blocks as generic as cobblestone sometimes...

`
[14:39:11] [Netty Epoll Server IO #3/ERROR] [FML]: There was a critical exception handling a packet on channel Waila
java.lang.RuntimeException: PLAYER target expects a Player arg
        at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$4.validateArgs(FMLOutboundHandler.java:125) ~[FMLOutboundHandler$OutboundTarget$4.class:?]
        at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:282) ~[FMLOutboundHandler.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[AbstractChannel.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:254) ~[SimpleNetworkWrapper.class:?]
        at mcp.mobius.waila.network.MessageRequestTile$Handler$1.run(MessageRequestTile.java:112) ~[MessageRequestTile$Handler$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) ~[MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
`

**Comment by TehNut** [comment]
Can either of you try with this build? http://tehnut.info/share/Hwyla-1.8.10-BCUSTOM_1.10.2.jar

Watch your log. If it's what I think it is, you should see an error spit out on occasion.

**Comment by aemondis** [comment]
I will give it a go... will report back in a little while.

**Comment by aemondis** [comment]
Immediate crash looking at the controller while doing a large crafting job... different error this time though:

[15:05:37] [Netty Epoll Server IO #1/ERROR] [FML]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
        at net.minecraft.network.play.server.SPacketCustomPayload.<init>(SPacketCustomPayload.java:27) ~[gl.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toS3FPackets(FMLProxyPacket.java:156) ~[FMLProxyPacket.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:531) ~[NetworkDispatcher.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[AbstractChannel.class:?]
        at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:247) [eo$4.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [SingleThreadEventExecutor.class:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [EpollEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by TehNut** [comment]
But I... what? Is that the entire error?

**Comment by aemondis** [comment]
That is the entire error, server side. Everything outside of that is completely normal.

Is there another log file somewhere else you are expecting additional debug in?

**Comment by TehNut** [comment]
Can you run `/dumphandlers` and send the file generated in the root dir of your modpack?

**Comment by aemondis** [comment]
As requested...

[WailaHandlerDump.zip](https://github.com/TehNut/HWYLA/files/773120/WailaHandlerDump.zip)

**Comment by TehNut** [comment]
I totally forgot to dump the NBT handlers. Welp. I'm going to do some testing on my end for a bit. Sorry about this.

**Comment by TehNut** [comment]
If you haven't already, could you try updating Hwyla on the server as well?

**Comment by aemondis** [comment]
Will get back to you shortly after updating server...

**Comment by aemondis** [comment]
The crash isn't occurring since the server restart with the new patched version...

**Comment by TehNut** [comment]
Are you seeing any errors in the server console?

**Comment by Eufranio** [comment]
Wanna some testing?

**Comment by ghost** [comment]
Can’t reproduce. Has this been fixed?

**Comment by TehNut** [comment]
Should have been but I keep getting people reporting it.

**Comment by TehNut** [comment]
Long since "fixed" by me giving up on the inventory display. It just isn't feasible.
