### ISSUE TITLE
Crash when picking up Super Circuit Maker Circuit

### ISSUE THREAD

**Issue by TheSomnambulist** [TehNut-Mods/HWYLA#53]
#### Issue Description:
So when I pick up a circuit from Super Circuit Maker, I get a crash.  The issue was reported on their github here (https://github.com/amadornes/SCM-Localization-Issues/issues/310).  And their fix of disabling waila does seem to work.  I am reporting here too, just in case.  

I am using a silk touch tinker's construct pick, and the crash seems to happen ~30% of the time.  The rest of the time, I just get the circuit as expected.

#### Steps to reproduce:
1.  Make a circuit from Super Circuit maker.  Doesn't have to be complex, but it cannot be blank.
2.  Break it with a silk touch pick.
3.  Repeat until Minecraft dies.

- Hwyla: 1.89-B23
- Minecraft:  1.10.2
- Forge:  12.18.3.2221
- Super Circuit Maker: 1.0.4

-Ticon:  2.6.2

Crash log here: https://paste.ee/p/q3kbB

**Comment by TehNut** [comment]
Try updating Hwyla (required on server as well). Although, this looks like an IC2 issue.

**Comment by TehNut** [comment]
Also, your crash is unrelated to the one in the linked issue.

**Comment by TheSomnambulist** [comment]
hmm, maybe i copied the wrong one....
edit:  Yup.  I'm a dummy.

**Comment by ChickenDuck** [comment]
@TehNut 

Same exact crash log here

**Steps to reproduce:**
Break a circuit from Super Circuit Maker while there is a redstone signal passing through

**Workaround:**
Disable all 3 redstone modules (vanilla.comparator, vanilla.redstone, vanilla.repeater) from HWYLA

**Client crash log:**
```
java.lang.NullPointerException: Unexpected error
	at com.amadornes.rscircuits.part.PartCircuit.getPickBlock(PartCircuit.java:952)
	at mcmultipart.multipart.MultipartContainer.getPickBlock(MultipartContainer.java:328)
	at mcmultipart.block.BlockMultipartContainer.getPickBlock(BlockMultipartContainer.java:144)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:182)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:90)
	at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:61)
	at mcp.mobius.waila.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:43)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickRender(WailaTickHandler.java:48)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_921_WailaTickHandler_tickRender_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:350)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1074)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by ghost** [comment]
I have the same issue. @ChickenDuck’s workaround totally worked for me, so thank you, @ChickenDuck!

Here’s my crash report: https://pastebin.com/raw/iqDcT2kT

I hope @TehNut will fix this.

**Comment by TehNut** [comment]
This isn't my crash to fix. The NPE goes into SCM code.
