### ISSUE TITLE
PLAYER target expects a Player arg (not sure if it's hwyla)

### ISSUE THREAD

**Issue by Eufranio** [TehNut-Mods/HWYLA#56]
Randomly the server started spamming this exception:
```
java.lang.RuntimeException: PLAYER target expects a Player arg
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$4.validateArgs(FMLOutboundHandler.java:125) ~[FMLOutboundHandler$OutboundTarget$4.class:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:282) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:254) [SimpleNetworkWrapper.class:?]
	at mcp.mobius.waila.network.MessageRequestTile$Handler$1.run(MessageRequestTile.java:111) [MessageRequestTile$Handler$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111-internal]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:235) [SpongeImplHooks.class:1.10.2-2221-5.1.0-BETA-2208]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zhm000(MinecraftServer.java:3931) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111-internal]
```
I'm not sure if the cause is HWYLA, but the only mod reference that I see is a HWYLA/Waila one, after sponge:
```
mcp.mobius.waila.network.MessageRequestTile$Handler$1.run(MessageRequestTile.java:111) [MessageRequestTile$Handler$1.class:?]
```
Versions:
- Hwyla: 1.10.2-1.8.10B24
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2239

My modpack: https://www.technicpack.net/modpack/magibeta-pack.940049/mods

**Comment by TehNut** [comment]
Make sure the client and server have the same version. #50

**Comment by Eufranio** [comment]
They have.
