### ISSUE TITLE
1.11.2 Client crash when looking at a furnace that uses a forestry sapling (red spruce sapling) as fuel

### ISSUE THREAD

**Issue by SableDrake** [TehNut-Mods/HWYLA#65]
#### Issue Description:
Client crash when looking at a furnace that uses a forestry sapling (red spruce sapling) as fuel

#### What happens:
client crashes

#### What you expected to happen:
it not to crash

#### Steps to reproduce:

1. put a red spruce sapling in the fuel slot of a furnace
2. put something smeltable into the top slot (like cobble)
3. crash
...
____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.8.13 B26
- Minecraft:  1.11.2
- Forge: 13.20.0.2279

#### Possible Conflicting Mods (Provide their version, as well)
bookshelf 1.5.0.363

#### WailaErrorOutput.txt

04/11/2017 - 09:09:02
renderStack | 64xitem.for.sapling@0
net.minecraft.util.ReportedException: Rendering item
	at net.darkhax.bookshelf.client.render.item.RenderItemWrapper.func_184391_a(RenderItemWrapper.java:316)
	at net.darkhax.bookshelf.client.render.item.RenderItemWrapper.func_180450_b(RenderItemWrapper.java:284)
	at mcp.mobius.waila.overlay.DisplayUtil.renderStack(DisplayUtil.java:85)
	at mcp.mobius.waila.overlay.tooltiprenderers.TTRenderStack.draw(TTRenderStack.java:52)
	at mcp.mobius.waila.overlay.Tooltip$Renderable.draw(Tooltip.java:223)
	at mcp.mobius.waila.overlay.Tooltip.draw2nd(Tooltip.java:182)
	at mcp.mobius.waila.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:81)
	at mcp.mobius.waila.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:44)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickRender(WailaTickHandler.java:48)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_648_WailaTickHandler_tickRender_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:350)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1075)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalArgumentException: itemStack must have nbt
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125)
	at forestry.core.genetics.Genome.getChromosome(Genome.java:139)
	at forestry.core.genetics.Genome.getActiveAllele(Genome.java:178)
	at forestry.arboriculture.genetics.TreeGenome.getSpecies(TreeGenome.java:49)
	at forestry.arboriculture.items.ItemGermlingGE.getColorFromItemstack(ItemGermlingGE.java:108)
	at forestry.core.models.ModelManager$ColoredItemItemColor.func_186726_a(ModelManager.java:226)
	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:139)
	at net.minecraft.client.renderer.RenderItem.func_175032_a(RenderItem.java:216)
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:130)
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:111)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:149)
	at net.minecraft.client.renderer.RenderItem.func_184390_a(RenderItem.java:308)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347)
	at net.darkhax.bookshelf.client.render.item.RenderItemWrapper.func_184391_a(RenderItemWrapper.java:303)
	... 21 more

**Comment by TehNut** [comment]
Only that one? Or any forestry sapling? Do non-forestry saplings crash?

**Comment by TehNut** [comment]
No response in 2 months. Closing.
